function(find_dirs_Cmakefile)
    file(GLOB dirs RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/*)
    message("Check dirs for test dir")
    foreach(dir ${dirs})
        if(IS_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/${dir})
            message("${dir}:found")
            if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${dir}/CMakeLists.txt")
                message("${dir}: found CMakeLists.txt")
                add_subdirectory(${dir})
            else()
                message("${dir}: no CMakeLists.txt ")
            endif()
        endif()
    endforeach()
endfunction()